---
title: "R Notebook"
output: 
  html_document:
    keep_md:  true
---

# ㅎㅇㅎㅇ




```r
library(foreign)
setwd("/Users/swayer/Desktop")
data <- read.spss("MethodData.sav",reencode='utf-8')
```

```
## re-encoding from utf-8
```



```r
data1 <- as.data.frame(data)
AA <- (data1$AA)
hist(AA)
```

![](과제_files/figure-html/unnamed-chunk-2-1.png)<!-- -->

```r
qqnorm(AA,main='Normal')
qqline(AA,col='red')
```

![](과제_files/figure-html/unnamed-chunk-2-2.png)<!-- -->

### 1-c

히스토그램도 대칭이고, 정규성검정 확인해보면 정규분포에 가깝다볼 수 있음.


## 2 


```r
library(dplyr)
```

```
## 
## Attaching package: 'dplyr'
```

```
## The following objects are masked from 'package:stats':
## 
##     filter, lag
```

```
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
```

```r
ex<- data1 %>% filter(exercise=='Medium'|exercise=='much')
ex_not <- data1 %>% filter(exercise=='A little'|exercise=='Not at all')
```

### 2-a



```r
ex_no <- ex_not[-24,]
a<- cbind(ex$wt_ch,ex_no$wt_ch)
t.test(a)
```

```
## 
## 	One Sample t-test
## 
## data:  a
## t = 4.8255, df = 45, p-value = 1.641e-05
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  1.013246 2.465015
## sample estimates:
## mean of x 
##   1.73913
```

```r
mean(ex$wt_ch)
```

```
## [1] 1.478261
```

```r
mean(ex_no$wt_ch)
```

```
## [1] 2
```

운동을 많이 하는 학생들, 적게 하는 학생들 뽑아보니 적게하는 학생들(ex_not)이 샘플갯수가 한개 더많아서

마지막 행 하나 삭제함 (23,23개로 맞춤)


통계가설

$H_0 :  \mu_{1} = \mu_2$

$H_1 :  \mu_{1} \neq \mu_2$
 

p-value가 0.00001641.. 로 < 0.05 .

통계적으로 유의하므로 귀무가설을 기각함 -> 두 집단 차이 존재함

두 집단 평균 비교해보면

운동한 사람들 1.4782, 안한 사람들 2로 

운동한 사람들의 체중변화가 더 작음.


### 2-b


```r
set <- cbind(data1$stress_r,data1$stress_g)
t.test(set)
```

```
## 
## 	One Sample t-test
## 
## data:  set
## t = 35.67, df = 93, p-value < 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  6.208458 6.940478
## sample estimates:
## mean of x 
##  6.574468
```

```r
mean(set[,1])
```

```
## [1] 7.297872
```

```r
mean(set[,2])
```

```
## [1] 5.851064
```

이 문제도 a와 같이 수업별 집단 간 스트레스 지수를 비교해보면 

귀무, 대립가설 똑같이 세우고

t검정 결과 두 집단 간 차이가 유의하여 귀무가설 기각

-> stress_r 수업의 스트레스 지수가 타수업의 그 것보다 높음


## 3


```r
cor(data1$HR1,data1$HR2)
```

```
## [1] 0.7168044
```

```r
cor(data1$HR1,data1$HR3)
```

```
## [1] 0.7013617
```

```r
cor(data1$HR2,data1$HR3)
```

```
## [1] 0.8755458
```

차례대로, $\rho_{12}=0.7168,\ \rho_{13}=0.70136,\ \rho_{23}=0.8755$



## 4 최적회귀식 결정

```r
nume_data <- data1[,c(6,7,9,10,11,14,15,16,17)]
cat_data <- data1[,c(3,4,5,8,13,19)]
head(cat_data)
```

```
##       Prog                   Spec Gender Glasses   Sit   exercise
## 1 master's             Philosophy Female     Yes Front   A little
## 2    Ph.D.               Pedagogy   Male      No Front     Medium
## 3 master's               Medicine Female      No Front     Medium
## 4 master's Leisure and Recreation Female     Yes Front     Medium
## 5 master's   Learning and Control Female      No Front   A little
## 6 master's Leisure and Recreation   Male      No Front Not at all
```

```r
final <- nume_data
head(final)
```

```
##   Age Hight  AA wt_ch exp_wtch stress_r stress_g Beer Coffee
## 1  31   169 2.8    -2       -2        9        7  1.0      2
## 2  38   172 4.1     0        0        3        3  0.5      1
## 3  23   163 3.4     2       -5        8        5  0.0      0
## 4  29   166 3.2     3       -5        8        6  5.0      3
## 5  23   168 3.7    -1       -4        7        5  0.8      1
## 6  28   176 3.2     0        0       10        5 20.0      7
```

```r
lm(AA~Age+Hight+wt_ch+exp_wtch+stress_r+stress_g+Beer+Coffee, data=final)
```

```
## 
## Call:
## lm(formula = AA ~ Age + Hight + wt_ch + exp_wtch + stress_r + 
##     stress_g + Beer + Coffee, data = final)
## 
## Coefficients:
## (Intercept)          Age        Hight        wt_ch     exp_wtch     stress_r  
##    4.149441     0.012342    -0.004677     0.034349     0.016257    -0.027382  
##    stress_g         Beer       Coffee  
##    0.019618    -0.030005     0.005469
```

수치를 추정하는 회귀식을 작성할 때 numeric data는 모두 고려하기로 하되, 

심박수 데이터는 위에서 확인했듯 각자 상관계수가 높아 독립변수 간 다중공선성 문제 여지가 있어서 제외

단순한 설명을 위해 명목형 변수도 제외

종합하면 회귀식은 아래와 같다

$AA = 4.149441+ 0.012342*Age -0.004677*Height + 0.034349*wt-ch + ..$


